//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sounds {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sounds.MiscStrings", typeof(MiscStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Artist.
        /// </summary>
        internal static string albumArtist {
            get {
                return ResourceManager.GetString("albumArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string albumArtistPrintf {
            get {
                return ResourceManager.GetString("albumArtistPrintf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There have been changes made to the playlist. Do you want to save your changes?.
        /// </summary>
        internal static string changeFileWhileDirty {
            get {
                return ResourceManager.GetString("changeFileWhileDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a track currently playing. Are you sure you want to stop playing the track and switch to another playlist?.
        /// </summary>
        internal static string changeFileWhilePlaying {
            get {
                return ResourceManager.GetString("changeFileWhilePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a track currently playing. Are you sure you want to stop playing the track and create a new playlist?.
        /// </summary>
        internal static string newFileWhilePlaying {
            get {
                return ResourceManager.GetString("newFileWhilePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string paused {
            get {
                return ResourceManager.GetString("paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string playing {
            get {
                return ResourceManager.GetString("playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a track currently playing. Are you sure you want to stop playing the track to quit the application?.
        /// </summary>
        internal static string quitWhilePlaying {
            get {
                return ResourceManager.GetString("quitWhilePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string stopped {
            get {
                return ResourceManager.GetString("stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Playlist.
        /// </summary>
        internal static string untitledPlaylist {
            get {
                return ResourceManager.GetString("untitledPlaylist", resourceCulture);
            }
        }
    }
}
